# Generated by Django 4.2 on 2023-08-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAssessts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_assesst', models.ImageField(blank=True, upload_to='photos/product/%y/%m/%d')),
                ('type_assesst', models.CharField(max_length=100, null=True, verbose_name='مكان صدور البطاقة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_Assessts', to='accounts.customer')),
            ],
        ),
    ]
