# Generated by Django 4.2 on 2023-08-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerassessts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerassessts',
            name='image_assesst',
            field=models.ImageField(blank=True, upload_to='photos/customer_assessts/%y/%m/%d'),
        ),
    ]
