# Generated by Django 4.2 on 2023-08-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customerassessts_image_assesst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم كامل'),
        ),
    ]
